<?php
    $this->headScript()->appendFile($this->baseUrl('scripts/jquery.min.js'));
    $this->headScript()->appendFile($this->baseUrl('scripts/workbench.js'));
    $this->headLink()->prependStylesheet($this->baseUrl('css/style.css'));
    $this->headLink()->prependStylesheet($this->baseUrl('css/reset.css'));
    $this->headTitle('Mainflow Workbench');
    header(" Content-Type: text/plain");
?>
<?php echo $this->doctype() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php
    echo $this->headMeta() . PHP_EOL;
    echo $this->headTitle() . PHP_EOL;
    echo $this->headLink() . PHP_EOL;
    echo $this->headStyle() . PHP_EOL;
    echo $this->headScript() . PHP_EOL;
?>
<script type="text/javascript">
    $(document).ready(function()
    {
        whenReady();
	});
</script>

</head>
<body>
    <div id="wrapper">
	    <div id="header">
            <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'module' => 'workbench')); ?>">
	          <img src="<?php echo $this->baseUrl('img/logo-mainflow.gif') ?>" alt="Mainflow" />
            </a>
	    </div>
		<div>
		    <?php echo $this->layout()->content ?>
		</div>
        <!-- <div id="fieldset-center" class="fieldset-center">blaat</div>-->
    </div>
</body>
</html>
